### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by olivroy** [mtennekes/cols4all#27]
Hi @mtennekes ,

Do you think it would be a good idea to release a new version soon in order to release tmap 4.0, and stop relying on the dev version in tmap?

Do you think it would be good to add a website for cols4all? You can do this with `usethis::use_pkgdown_github_pages()`.

**Comment by mtennekes** [comment]
@olivroy yes, indeed, but `cols4all` is also undergoing some change at the moment (some nice features, worth checking out). When those are finished (I expect in two weeks), I'll release a new version to CRAN.

Good idea about that website!

**Comment by olivroy** [comment]
sounds good! excited to see the new features!

**Comment by mtennekes** [comment]
The package should be okayish for the next CRAN release. I've executed `usethis::use_pkgdown_github_pages()`. Could you check if it works well @olivroy ?

**Comment by olivroy** [comment]
All great https://mtennekes.github.io/cols4all/reference/index.html! Thanks

**Comment by mtennekes** [comment]
Hmmm, I've got problems with including a local png file into the vignette. Originally, I placed them into https://github.com/mtennekes/cols4all/issues/1, but since GitHub has been more private, the urls are nut public anymore.

I've tried placing it in the /vignettes, /doc, /man/figures, but without luck...

Could you check @olivroy See https://win-builder.r-project.org/g4S3SYaJb991/

**Comment by mtennekes** [comment]
Version 0.7 accepted on CRAN :-)
